name: Testing access secrets from script

on:
  workflow_dispatch:
  
jobs:
  testing_case:
    name: Testing access secrets from script
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v1
      - name: testing access secrets
        run: |
          chmod +x "${GITHUB_WORKSPACE}/test_access_secret.sh"
          source "${GITHUB_WORKSPACE}/test_access_secret.sh"
