name: Testing secrets

on:
  workflow_dispatch:
  
jobs:
  testing_case:
    name: Testing access secrets from script
    runs-on: ubuntu-latest
    steps:
     - name: testing secrets
       run: |
         SECRET=$(read ${{ secrets.SECRET_ACCESSED_FROM_SCRIPT }} << "EOF")
