name: Testing case

on:
  workflow_dispatch:
  inputs:
      database_type:
jobs:
  testing_case:
    runs_on: ubuntu-latest
    steps:
      - name: testing case
      run: |
      case ${{ github.event.inputs.database_type }} in
      mysql)
        SITE_DATABASE="Es un mysql" ;;
      postgresql)
        SITE_DATABASE="Es un postgresql" ;;
      esca
      
      echo ${SITE_DATABASE}
