name: Trim spaces

on:
  workflow_dispatch:
    inputs:
      site_names:
jobs:
  trim_spaces:
    name: Trim Spaces
    runs-on: ubuntu-latest
    steps:
    - name: Prepare Input
      id: prepare-input
      run: |
        FORMATTED_INPUT=$(echo ${{ github.event.inputs.site_names }} | xargs)
        echo ${FORMATTED_INPUT}
        echo "::set-output name=FORMATTED_SITE_NAME::${FORMATTED_INPUT}"
    - name: Echo Input
      run: |
        echo ${{ steps.prepare-input.outputs.FORMATTED_SITE_NAME }}   
