name: Trim spaces

on:
  workflow_dispatch:
    inputs:
      site_names:
jobs:
  trim_spaces:
    name: Trim Spaces
    runs-on: ubuntu-latest
    steps:
    - name: Prepare Input
      id: prepare-input
      run: |
        FORMATTED_INPUT=$(echo ${{ github.event.inputs.site_names }} | sed 's/ //g')
        echo "::set-output name=site_name::${FORMATTED_INPUT}"
    - name: Echo Input
      run: |
        echo ${{ needs.prepare-input.outputs.site_name }}
        
